version: '3'

services:
  app:
    container_name: app
    image: node:16
    working_dir: /var/www/html/
    command: bash -c "npm install && node index.js"
    tty: true
    networks:
      - dbnet
      - appnet
    environment:
      - MYSQL_HOST=app-db-mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=app
    volumes:
      - ./node/:/var/www/html/

  proxy:
    container_name: app-proxy
    build: 
      context: nginx
    image: joaocsv/nginx-app-proxy
    networks:
      - appnet
    ports:
      - 8080:80
  
  db-mysql:
    container_name: app-db-mysql
    build:
      context: mysql
    image: joaocsv/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - dbnet
    
networks:
  appnet:
    driver: bridge
  dbnet:
    driver: bridge