version: '3'

services:
  app:
    container_name: app
    build:
      context: node  
    image: joaocsv/node-app
    networks:
      - appnet
    tty: true

  proxy:
    container_name: app-proxy
    build: 
      context: nginx
    image: joaocsv/nginx-app-proxy
    networks:
      - appnet
    ports:
      - 8080:80

networks:
  appnet:
    driver: bridge